# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

ENV MCP_CLIENT_DOCKER=true
# Create app directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies without triggering any unwanted scripts
RUN npm install --ignore-scripts

# Run post-install script for @vscode/ripgrep to download the binary
RUN npm rebuild @vscode/ripgrep

# Copy all source code
COPY . .

# Build the application
RUN npm run build

# Expose Streamable HTTP port (solo se usa en modo http: `node dist/http.js`).
EXPOSE 8080

# Command to run the server (modo stdio por defecto).
# Modo HTTP tras Tailscale Funnel:
#   docker run -e MCP_HTTP_TOKEN=<token> -e MCP_HTTP_ALLOWED_HOSTS=<nodo>.ts.net \
#     -p 127.0.0.1:8080:8080 <img> node dist/http.js
CMD [ "node", "dist/index.js" ]
